/*
 * Built-in demo: a realistic package-lock.json (v3) for a small Express app,
 * with deliberately duplicated libraries (ms ×3, debug ×2, lodash ×2) so the
 * anomaly detector has something to find. All names/versions are real
 * published packages, so "fetch real sizes from npm" works on it too.
 */
(function (global) {
    'use strict';
    global.BLOAT_SAMPLE_LOCK = {
        name: 'demo-express-app',
        version: '1.0.0',
        lockfileVersion: 3,
        requires: true,
        packages: {
            '': {
                name: 'demo-express-app',
                version: '1.0.0',
                dependencies: { axios: '^1.6.0', chalk: '^4.1.2', express: '^4.18.2', lodash: '^4.17.21', uuid: '^9.0.1' },
                devDependencies: { 'cli-table2': '^0.2.0', nodemon: '^3.0.1', webpack: '^5.89.0' },
            },
            'node_modules/accepts': { version: '1.3.8', dependencies: { 'mime-types': '~2.1.34', negotiator: '0.6.3' } },
            'node_modules/acorn': { version: '8.11.2', dev: true },
            'node_modules/ajv': { version: '6.12.6', dev: true, dependencies: { 'fast-deep-equal': '^3.1.1', 'fast-json-stable-stringify': '^2.0.0', 'json-schema-traverse': '^0.4.1', 'uri-js': '^4.2.2' } },
            'node_modules/ansi-styles': { version: '4.3.0', dependencies: { 'color-convert': '^2.0.1' } },
            'node_modules/asynckit': { version: '0.4.0' },
            'node_modules/axios': { version: '1.6.2', dependencies: { 'follow-redirects': '^1.15.0', 'form-data': '^4.0.0' } },
            'node_modules/body-parser': { version: '1.20.1', dependencies: { bytes: '3.1.2', debug: '2.6.9', qs: '6.11.0' } },
            'node_modules/braces': { version: '3.0.2', dev: true, dependencies: { 'fill-range': '^7.0.1' } },
            'node_modules/bytes': { version: '3.1.2' },
            'node_modules/chalk': { version: '4.1.2', dependencies: { 'ansi-styles': '^4.1.0', 'supports-color': '^7.1.0' } },
            'node_modules/chokidar': { version: '3.5.3', dev: true, dependencies: { braces: '~3.0.2' } },
            'node_modules/cli-table2': { version: '0.2.0', dev: true, dependencies: { colors: '1.0.3', lodash: '^3.10.1', 'string-width': '^1.0.1' } },
            'node_modules/cli-table2/node_modules/lodash': { version: '3.10.1', dev: true },
            'node_modules/colors': { version: '1.0.3', dev: true },
            'node_modules/color-convert': { version: '2.0.1', dependencies: { 'color-name': '~1.1.4' } },
            'node_modules/color-name': { version: '1.1.4' },
            'node_modules/combined-stream': { version: '1.0.8', dependencies: { 'delayed-stream': '~1.0.0' } },
            'node_modules/cookie': { version: '0.5.0' },
            'node_modules/debug': { version: '2.6.9', dependencies: { ms: '2.0.0' } },
            'node_modules/debug/node_modules/ms': { version: '2.0.0' },
            'node_modules/delayed-stream': { version: '1.0.0' },
            'node_modules/depd': { version: '2.0.0' },
            'node_modules/enhanced-resolve': { version: '5.15.0', dev: true, dependencies: { 'graceful-fs': '^4.2.4', tapable: '^2.2.0' } },
            'node_modules/express': { version: '4.18.2', dependencies: { accepts: '~1.3.8', 'body-parser': '1.20.1', cookie: '0.5.0', debug: '2.6.9', qs: '6.11.0', 'safe-buffer': '5.2.1', send: '0.18.0', 'serve-static': '1.15.0' } },
            'node_modules/fast-deep-equal': { version: '3.1.3', dev: true },
            'node_modules/fast-json-stable-stringify': { version: '2.1.0', dev: true },
            'node_modules/fill-range': { version: '7.0.1', dev: true, dependencies: { 'to-regex-range': '^5.0.1' } },
            'node_modules/follow-redirects': { version: '1.15.3' },
            'node_modules/form-data': { version: '4.0.0', dependencies: { asynckit: '^0.4.0', 'combined-stream': '^1.0.8', 'mime-types': '^2.1.12' } },
            'node_modules/fresh': { version: '0.5.2' },
            'node_modules/glob-to-regexp': { version: '0.4.1', dev: true },
            'node_modules/graceful-fs': { version: '4.2.11', dev: true },
            'node_modules/has-flag': { version: '4.0.0' },
            'node_modules/http-errors': { version: '2.0.0', dependencies: { depd: '2.0.0', statuses: '2.0.1' } },
            'node_modules/is-number': { version: '7.0.0', dev: true },
            'node_modules/json-schema-traverse': { version: '0.4.1', dev: true },
            'node_modules/lodash': { version: '4.17.21' },
            'node_modules/mime': { version: '1.6.0' },
            'node_modules/mime-db': { version: '1.52.0' },
            'node_modules/mime-types': { version: '2.1.35', dependencies: { 'mime-db': '1.52.0' } },
            'node_modules/ms': { version: '2.1.3' },
            'node_modules/negotiator': { version: '0.6.3' },
            'node_modules/nodemon': { version: '3.0.1', dev: true, dependencies: { chokidar: '^3.5.2', debug: '^4', semver: '^7.5.3' } },
            'node_modules/nodemon/node_modules/debug': { version: '4.3.4', dev: true, dependencies: { ms: '2.1.2' } },
            'node_modules/nodemon/node_modules/ms': { version: '2.1.2', dev: true },
            'node_modules/punycode': { version: '2.3.1', dev: true },
            'node_modules/qs': { version: '6.11.0' },
            'node_modules/safe-buffer': { version: '5.2.1' },
            'node_modules/schema-utils': { version: '3.3.0', dev: true, dependencies: { ajv: '^6.12.5' } },
            'node_modules/semver': { version: '7.5.4', dev: true },
            'node_modules/send': { version: '0.18.0', dependencies: { debug: '2.6.9', fresh: '0.5.2', 'http-errors': '2.0.0', mime: '1.6.0', ms: '2.1.3' } },
            'node_modules/serve-static': { version: '1.15.0', dependencies: { send: '0.18.0' } },
            'node_modules/statuses': { version: '2.0.1' },
            'node_modules/string-width': { version: '1.0.2', dev: true },
            'node_modules/supports-color': { version: '7.2.0', dependencies: { 'has-flag': '^4.0.0' } },
            'node_modules/tapable': { version: '2.2.1', dev: true },
            'node_modules/to-regex-range': { version: '5.0.1', dev: true, dependencies: { 'is-number': '^7.0.0' } },
            'node_modules/uri-js': { version: '4.4.1', dev: true, dependencies: { punycode: '^2.1.0' } },
            'node_modules/uuid': { version: '9.0.1' },
            'node_modules/watchpack': { version: '2.4.0', dev: true, dependencies: { 'glob-to-regexp': '^0.4.1', 'graceful-fs': '^4.1.2' } },
            'node_modules/webpack': { version: '5.89.0', dev: true, dependencies: { acorn: '^8.7.1', 'enhanced-resolve': '^5.15.0', 'schema-utils': '^3.2.0', tapable: '^2.1.1', watchpack: '^2.4.0' } },
        },
    };
})(typeof window !== 'undefined' ? window : globalThis);
